name: Docs

on:
  push:
    branches: [ "main" ]
    paths:
        - 'docs/**'
        - .github/workflows/mkdocs.yml

permissions:
  contents: write
  packages: write
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Deploy mkdocs keeping helm chart files
      run: |
        curl https://raw.githubusercontent.com/esgi-lyon/paas-tutorial/gh-pages/index.yaml > docs/index.yaml
        mkdocs gh-deploy --force
